### ISSUE TITLE
Demo site?

### ISSUE THREAD

**Issue by ghost** [aziascreations/Simple-Chan#1]
Is there a demo site for this project?

**Comment by aziascreations** [comment]
I can't really host a demo site since the application does not feature any real protection against spamming and code injection.

But here is a small video showcasing the application, I hope it works for you:

https://user-images.githubusercontent.com/7206320/125976215-0c31b306-3b94-4cc4-841f-b3e2c2c8dbd7.mp4

**Comment by ghost** [comment]
> I can't really host a demo site since the application does not feature any real protection against spamming and code injection.
> 
> But here is a small video showcasing the application, I hope it works for you:
> 
>  lGSN8Qk4Sx.mp4

Looks very clean and cool, thanks. Hope you'll be able to make a demo site and/or installation instructions soon.

**Comment by aziascreations** [comment]
Thank you, I updated the readme and the application to includes launch arguments for the port and boards.
You can also find a precompiled fat jar in the release section.

You should be able to compile it with Gradle, but I'm getting weird errors outside of Idea at the moment.

This should be fixed in the future, and the look of the web pages too since I've been updating the stylesheet for the last couple of days.
